# Generated by Django 6.0.6 on 2026-06-21 14:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('barangay_name', models.CharField(max_length=255)),
                ('region_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city_code', models.CharField(blank=True, max_length=50, null=True)),
                ('barangay_code', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=200, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('status', models.CharField(max_length=100)),
                ('paid_status', models.BooleanField(default=False)),
                ('ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.owner')),
            ],
        ),
    ]
