# Generated by Django 6.0.6 on 2026-07-06 01:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('date_owned', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_declaration', models.CharField(max_length=255)),
                ('tax_payment_status', models.CharField(max_length=100)),
                ('market_value', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='active', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('parcel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('area_auto_m2', models.FloatField(blank=True, null=True)),
                ('area_declared', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('status', models.CharField(default='active', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.owner')),
                ('tax_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.taxinformation')),
            ],
        ),
    ]
