# Generated by Django 6.0.6 on 2026-07-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=100, null=True),
        ),
    ]
