# Generated by Django 6.0.6 on 2026-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Boundary',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='paid_status',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='status',
        ),
    ]
