# Generated by Django 6.0.6 on 2026-07-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
