# Generated by Django 6.0.6 on 2026-07-05 14:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_taxinformation_delete_boundary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='date_owned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='classification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='market_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='tax_declaration',
            field=models.CharField(default='UNKNOWN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='tax_payment_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=200, unique=True)),
                ('area_auto', models.FloatField(blank=True, null=True)),
                ('area_declared', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('status', models.CharField(default='active', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.owner')),
                ('tax_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.taxinformation')),
            ],
        ),
        migrations.DeleteModel(
            name='Parcels',
        ),
    ]
