# Generated by Django 6.0.6 on 2026-07-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='baragay_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
