# Generated by Django 6.0.6 on 2026-07-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_parcel_baragay_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='baragay_name',
            new_name='barangay_name',
        ),
    ]
