# Generated by Django 6.0.6 on 2026-07-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_rename_baragay_name_parcel_barangay_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='area_auto_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area_auto_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='area_declared',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='taxinformation',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
