# Generated by Django 6.0.6 on 2026-07-05 00:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('province_name', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('barangay_name', models.CharField(max_length=255)),
                ('region_code', models.CharField(blank=True, max_length=50, null=True)),
                ('province_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city_code', models.CharField(blank=True, max_length=50, null=True)),
                ('barangay_code', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
